version: "3.8"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:

  snyk_exporter:
    container_name: snyk_exporter
    hostname: snyk_exporter
    image: grafana/snyk_exporter
    command:
      - '--log.level=info'
      - '--snyk.api-token=8dc0b1e2-682d-4b11-820b-9c46326ff331'
      - '--snyk.interval=75'
      - '--snyk.organization=d0138106-2e76-4174-980b-e31daac65cc6'
      - '--snyk.organization=10f6c201-a59a-4a87-8aa8-a8f576567b76'
      - '--snyk.timeout=60'
    ports:
      - 9532:9532

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    links:
      - snyk_exporter:snyk_exporter
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    volumes:
      - ./grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./grafana_dashboards.yml:/etc/grafana/provisioning/dashboards/all.yaml
      - ./grafana_dashboards:/var/lib/grafana/dashboards
      - ./grafana_config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
