{
 "title": "Snyk Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Project",
    "query": "query_result(topk(10, sort_desc(sum(snyk_vulnerabilities_total) by (project))))"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Vulnerabilities per Project",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total) by (project)"
    }
   ]
  },
  { "title": "$Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "Project" },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"high\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"medium\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"low\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Ignored",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Issue Count History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(severity) (snyk_vulnerabilities_total{project=~\"$Project\"})",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Issues by Type",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{project=\"$Project\"}) by (issue_title)"
    }
   ]
  },
  { "title": "$Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"high\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"medium\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"low\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Ignored",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Issue Count History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(severity) (snyk_vulnerabilities_total{ignored=\"false\", project=~\"$Project\"})",
     "legendFormat": "{{severity}}"
    },
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\",project=~\"$Project\"})",
     "legendFormat": "ignored"
    }
   ]
  },
  {
   "title": "Issues by Type",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{project=\"$Project\"}) by (issue_title)"
    }
   ]
  },
  { "title": "$Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"high\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"medium\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"low\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Ignored",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Issue Count History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(severity) (snyk_vulnerabilities_total{ignored=\"false\", project=~\"$Project\"})",
     "legendFormat": "{{severity}}"
    },
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\",project=~\"$Project\"})",
     "legendFormat": "ignored"
    }
   ]
  },
  {
   "title": "Issues by Type",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{project=\"$Project\"}) by (issue_title)"
    }
   ]
  },
  { "title": "$Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"high\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"medium\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"low\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Ignored",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Issue Count History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(severity) (snyk_vulnerabilities_total{ignored=\"false\", project=~\"$Project\"})",
     "legendFormat": "{{severity}}"
    },
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\",project=~\"$Project\"})",
     "legendFormat": "ignored"
    }
   ]
  },
  {
   "title": "Issues by Type",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{project=\"$Project\"}) by (issue_title)"
    }
   ]
  },
  { "title": "$Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"high\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"medium\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"low\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Ignored",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Issue Count History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(severity) (snyk_vulnerabilities_total{ignored=\"false\", project=~\"$Project\"})",
     "legendFormat": "{{severity}}"
    },
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\",project=~\"$Project\"})",
     "legendFormat": "ignored"
    }
   ]
  },
  {
   "title": "Issues by Type",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{project=\"$Project\"}) by (issue_title)"
    }
   ]
  },
  { "title": "$Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"high\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"medium\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"low\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Ignored",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Issue Count History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(severity) (snyk_vulnerabilities_total{ignored=\"false\", project=~\"$Project\"})",
     "legendFormat": "{{severity}}"
    },
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\",project=~\"$Project\"})",
     "legendFormat": "ignored"
    }
   ]
  },
  {
   "title": "Issues by Type",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{project=\"$Project\"}) by (issue_title)"
    }
   ]
  },
  { "title": "$Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"high\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"medium\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"low\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Ignored",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Issue Count History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(severity) (snyk_vulnerabilities_total{ignored=\"false\", project=~\"$Project\"})",
     "legendFormat": "{{severity}}"
    },
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\",project=~\"$Project\"})",
     "legendFormat": "ignored"
    }
   ]
  },
  {
   "title": "Issues by Type",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{project=\"$Project\"}) by (issue_title)"
    }
   ]
  },
  { "title": "$Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"high\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"medium\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"low\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Ignored",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Issue Count History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(severity) (snyk_vulnerabilities_total{ignored=\"false\", project=~\"$Project\"})",
     "legendFormat": "{{severity}}"
    },
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\",project=~\"$Project\"})",
     "legendFormat": "ignored"
    }
   ]
  },
  {
   "title": "Issues by Type",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 66 },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{project=\"$Project\"}) by (issue_title)"
    }
   ]
  },
  { "title": "$Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"high\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"medium\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"low\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Ignored",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Issue Count History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(severity) (snyk_vulnerabilities_total{ignored=\"false\", project=~\"$Project\"})",
     "legendFormat": "{{severity}}"
    },
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\",project=~\"$Project\"})",
     "legendFormat": "ignored"
    }
   ]
  },
  {
   "title": "Issues by Type",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 74 },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{project=\"$Project\"}) by (issue_title)"
    }
   ]
  },
  { "title": "$Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"high\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"medium\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"low\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Ignored",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Issue Count History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(severity) (snyk_vulnerabilities_total{ignored=\"false\", project=~\"$Project\"})",
     "legendFormat": "{{severity}}"
    },
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\",project=~\"$Project\"})",
     "legendFormat": "ignored"
    }
   ]
  },
  {
   "title": "Issues by Type",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 82 },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{project=\"$Project\"}) by (issue_title)"
    }
   ]
  }
 ]
}